# Generated by Django 5.2.8 on 2026-05-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('friend', 'Friend'), ('family', 'Family'), ('work', 'Work'), ('emergency', 'Emergency'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
